- package:
  - name: cardano-wallet-http-bridge
  - section:
    - name: test:integration
    - message:
      - name: Weeds exported
      - module:
        - name: Test.Integration.Framework.DSL
        - identifier:
          - </>
          - expectError
          - expectSuccess
          - getFromResponse
      - module:
        - name: Test.Integration.Framework.Request
        - identifier:
          - ClientError
          - DecodeFailure
          - NonJson
          - None
          - unsafeRequest
  - section:
    - name: test:unit
    - message:
      - name: Weeds exported
      - module:
        - name: Spec
        - identifier: main
- package:
  - name: cardano-wallet-launcher
  - section:
    - name: library
    - message:
      - name: Module not compiled
      - module: Cardano.Launcher.Windows

- package:
  - name: cardano-wallet-jormungandr
  - section:
    - name: test:unit
    - message:
      - name: Weeds exported
      - module:
        - name: Spec
        - identifier: main

